name: calendar

on:
  schedule:
    - cron: "30 0 * * *"    #runs at 00:30 UTC everyday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
          run: |
            python -m pip install --upgrade pip
            pip install -r ${GITHUB_WORKSPACE}/requirements.txt
          ref: # branch
            master
      - name: execute py script # run file
        run: |
          pwd
          python ${GITHUB_WORKSPACE}/calendar.py -u "https://export.kalender.digital/ics/573896/f6d3f9c540594317cc03/tsvjugendraum.ics" -o ./public/info.ics
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
